packagecloud: &packagecloud
  provider: packagecloud
  username: cs50
  repository: php-cs50
  token: $PACKAGECLOUD_TOKEN
  local-dir: build/deb
  package_glob: *.deb
  skip_cleanup: true
  on:
    branch: master

branches:
  except: "/^v\\d/"
before_install: gem install fpm
install: true
script: make deb
deploy:
  # 12.04
  - <<: *packagecloud
    dist: ubuntu/precise

  # 12.10
  - <<: *packagecloud
    dist: ubuntu/quantal

  # 13.04
  - <<: *packagecloud
    dist: ubuntu/raring

  # 13.10
  - <<: *packagecloud
    dist: ubuntu/saucy

  # 14.04
  - <<: *packagecloud
    dist: ubuntu/trusty

  # 14.10
  - <<: *packagecloud
    dist: ubuntu/utopic

  # 15.04
  - <<: *packagecloud
    dist: ubuntu/vivid

  # 15.10
  - <<: *packagecloud
    dist: ubuntu/wily

  # 16.04
  - <<: *packagecloud
    dist: ubuntu/xenial

  # 16.10
  - <<: *packagecloud
    dist: ubuntu/yakkety

  # 17.04
  - <<: *packagecloud
    dist: ubuntu/zesty

  # 17.10
  - <<: *packagecloud
    dist: ubuntu/artful

  # 18.04
  - <<: *packagecloud
    dist: ubuntu/bionic

  - provider: script
    script: 'curl --fail --data "{ \"tag_name\": \"v$(make version)\",
      \"target_commitish\": \"$TRAVIS_COMMIT\", \"name\": \"v$(make version)\"
    }" --user bot50:$GITHUB_TOKEN https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases'
    on:
      branch: master
notifications:
  slack:
    secure: D2d4GpU6R9GDizy7zmfS4bPWgYFZ6snMlAWyQ8LfC1uA4ZgT99ktkwQRmtvvLRLrTM9snRCEJE5gm6z2NRmQLGfqJ6yIgdLYUCLRY3N+ZyR+MGHQBljwnqzFWdo2KaTcP96Q9vj09Mv28Pq3jcDt351FgXMDMKedfcW04lW4Qgw=
